### ISSUE TITLE
use lib for ansi color support

### ISSUE THREAD

**Issue by willkg** [rehandalal/therapist#10]
This file is doing ansi color code stuff:

https://github.com/rehandalal/therapist/blob/master/therapist/printer.py

However, I suggest you not roll your own and instead do it with click or blessings or one of the other libs that takes into account terminal types and tty and a bunch of other things.

* click: http://click.pocoo.org/5/utils/#ansi-colors
* blessings: https://pypi.python.org/pypi/blessings
* blessed (fork of blessings): http://blessed.readthedocs.io/en/latest/overview.html

When I wrote francis, I used the click support. It's limited in its color choices, but was good enough to not require another library:

https://github.com/willkg/francis/blob/c727fa5eaa77662277f95fbf000f7afc71cbbed4/francis/cmdline.py#L521

**Comment by rehandalal** [comment]
Yeah I was actually looking at using [couleur](https://github.com/gabrielfalcao/couleur) to do this.

**Comment by rehandalal** [comment]
^
