### ISSUE TITLE
Staged files are deleted with commit signing and failed passphrase entry

### ISSUE THREAD

**Issue by Osmose** [rehandalal/therapist#14]
This was tested on OSX using GPG and pinentry-mac from Homebrew for entering my GPG passphrase. I suspect the method of passphrase entry doesn't really matter.

1. Set up a git repo with the Therapist pre-commit hook.
2. Set up [automatic commit signing](https://harryrschwartz.com/2014/11/01/automatically-signing-your-git-commits.html). You might be able to replicate this with just a single signed commit too.
3. Create a new file, say `newfile.txt`.
4. Stage and attempt to commit the file.
5. You'll be prompted for your GPG password before therapist runs any configured jobs. Cancel out of the prompt or let it time out.
6.  If prompted for a commit message, use a blank one to abort commit.

The end result is that all the staged files are gone. There's no new refs in the reflog, either. It also fails if you provide a message, you'll just be prompted a second time for your password, which you must cancel out of.

@mythmon suspects that this has to do with the fact that stashes are also signed, and cancelling out of signing makes the stash fail.

**Comment by mythmon** [comment]
I also suspect that this is OSX specific. On Linux, I've had GPG signing fail often, and I don't think it has caused therapist to delete things for me. The steps to reproduce don't produce the issue for me.

**Comment by rehandalal** [comment]
Fixed by #15
