### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by leplatrem** [rehandalal/therapist#177]
https://github.com/Kinto/kinto/pull/2800 is stuck because of:
```
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The conflict is caused by:
    black 21.5b2 depends on pathspec<1 and >=0.8.1
    therapist 2.1.0 depends on pathspec==0.8.0
```

`pathspec==0.8.1` is already on the `main` branch, so releasing would help!

Thank you!!

> PS: As for a long-term solution, I think we could loosen the dependencies, like remove the minor version [here](https://github.com/rehandalal/therapist/blob/aaa53779b9533573b63197ae986b2df7c3a306da/setup.py#L17)

**Comment by rehandalal** [comment]
i'll get a new release up this evening

**Comment by rehandalal** [comment]
New version has been released. Sorry about the delay been busy onboarding at the new job.

**Comment by leplatrem** [comment]
Argh!

It doesn't behave as intended  :(  Sorry for misleading you on this one :( 

```
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The conflict is caused by:
    black 21.6b0 depends on pathspec<1 and >=0.8.1
    therapist 2.1.1 depends on pathspec==0.8
```

**Comment by rehandalal** [comment]
damn. i'll update and release a new version shortly.

**Comment by rehandalal** [comment]
@leplatrem special order just for you it's v2.1.2 that drops version numbers from setup.py completely. lmk if this works for you now.
