### ISSUE TITLE
AttirbuteError

### ISSUE THREAD

**Issue by amor71** [rehandalal/therapist#181]
I've been using the project for a while. Today I got this new error, which trying to commit:

`AttributeError: 'NoneType' object has no attribute 'groups'`

Happy to get directions on how to resolve it..

**Comment by amor71** [comment]
Found work around. The issue happened when doing `git commit -a`. However `git commit` works just fine. later `git commit -a` is back to life. Wierd I know.

**Comment by rehandalal** [comment]
Thanks for filing this issue. This is definitely an edge case we should be handling. I don't suppose you could rewind to the commit that was experiencing the problem and re-stage the files using `git add .` and then send me the output for `git status --porcelain`? That would really help with debugging the issue.

**Comment by amor71** [comment]
@rehandalal Thank you for the quick response. I believe the issue has to do w/ weird situation of renaming files in the git-repo. I will try to reproduce it later in the week.

**Comment by rehandalal** [comment]
I believe the fix in #182 should resolve the edge case that caused the `AttributeError`. Git status parsing should now be a lot more reliable.

I'll put out a new release in the next day or two. Feel free to re-open if you run into the issue again after upgrading.
