### ISSUE TITLE
therapist run skip black

### ISSUE THREAD

**Issue by VietThan** [rehandalal/therapist#197]
Hello 👋 , this is similar to #51 and I tried staging the files but getting skips

**Environment**
Using python3.9, homebrew install, Mac Pro M1, zsh

**Steps to reproduce:**

```bash
$ mkdir therapist-test
$ cd therapist-test
$ export VENV=$(pwd)/env
$ python3 -m venv $VENV
$ git init
$ touch test.py
$ echo "def hello(): print('hello world')" >> test.py
$ echo "hello()" >> test.py
$ $VENV/bin/pip3 install therapist
$ $VENV/bin/pip3 install black
$ #create yaml .therapist.yml with black
$ $VENV/bin/therapist install 
Installing pre-commit hook...	DONE
$ git add test.py
$ $VENV/bin/therapist run 
black ............................................................... [SKIPPED]
-------------------------------------------------------------------------------
Completed in: 0.0s
```

.therapist.yml content:

```yaml
actions:
     black:
         run: black -l 79 {files}
         include: “*.py”
```

**Expected output:**
Not skips

**Comment by rehandalal** [comment]
@VietThan thanks for the issue report. i'm going to try to wire up a unit test to reproduce your issue. 

one thing i notice above (and i just want to rule it out) is that you are not using standard quotes in the provided .yml file. You aren't using `"` you're using `“` and `”` which will not get parsed correctly.

**Comment by rehandalal** [comment]
Glad that worked out!
