### ISSUE TITLE
Add plugins

### ISSUE THREAD

**Issue by rehandalal** [rehandalal/therapist#3]
Having some plugins that are capable of performing common linting tasks such as: checking for blank lines at the end of files, ensuring that large files have not been added, etc. would be useful.

These should have be extras with optional dependencies: http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by willkg** [comment]
If you support dynamic discovery, then other people could write plugins as separate python projects.

http://setuptools.readthedocs.io/en/latest/setuptools.html#extensible-applications-and-frameworks
